-- 1) Tabela de itens do catalogo
create table if not exists public.catalog_items (
  id bigint generated by default as identity primary key,
  category text not null,
  title text not null,
  image_url text not null,
  created_at timestamp with time zone not null default now()
);

-- 2) RLS ligado
alter table public.catalog_items enable row level security;

-- 3) Leitura publica (site)
drop policy if exists "catalog_select_public" on public.catalog_items;
create policy "catalog_select_public"
on public.catalog_items
for select
using (true);

-- 4) Insercao somente por seu usuario admin autenticado
-- Troque o email abaixo pelo seu email real do Supabase Auth

drop policy if exists "catalog_insert_admin_only" on public.catalog_items;
create policy "catalog_insert_admin_only"
on public.catalog_items
for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'gmstudio3d@gmail.com');

-- 5) (Opcional) permitir delete/update so para admin

drop policy if exists "catalog_update_admin_only" on public.catalog_items;
create policy "catalog_update_admin_only"
on public.catalog_items
for update
to authenticated
using ((auth.jwt() ->> 'email') = 'gmstudio3d@gmail.com')
with check ((auth.jwt() ->> 'email') = 'gmstudio3d@gmail.com');

drop policy if exists "catalog_delete_admin_only" on public.catalog_items;
create policy "catalog_delete_admin_only"
on public.catalog_items
for delete
to authenticated
using ((auth.jwt() ->> 'email') = 'gmstudio3d@gmail.com');

